remote_theme           : "mmistakes/minimal-mistakes"
url: "https://wooseunghoon.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

title: Sun's Blog
subtitle: "HyeSun's Blog :)"
email: gptjs409@gmail.com
name: Choi HyeSun
description: >
  This is Blog for Study & Work & Hobby
