name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 빌드할 브랜치명

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x # 필요한 Ruby 버전을 입력하세요.

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Build
        run: |
          bundle install
          bundle exec jekyll build --destination=./build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build